import type { MenuItem, User } from './types';

export const initialMenuItems: MenuItem[] = [
  {
    id: 'm1',
    name: 'Nasi Goreng Spesial',
    category: 'Makanan Berat',
    price: 15000,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop&auto=format',
    description: 'Nasi goreng dengan telur, ayam, dan sayuran segar',
    emoji: '🍳',
  },
  {
    id: 'm2',
    name: 'Ayam Geprek Sambal Bawang',
    category: 'Makanan Berat',
    price: 18000,
    stock: 15,
    image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=300&fit=crop&auto=format',
    description: 'Ayam crispy digeprek dengan sambal bawang spesial pedas',
    emoji: '🍗',
  },
  {
    id: 'm3',
    name: 'Mie Ayam Bakso',
    category: 'Makanan Berat',
    price: 13000,
    stock: 0,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&h=300&fit=crop&auto=format',
    description: 'Mie kuning dengan ayam cincang, bakso, dan kuah kaldu sapi',
    emoji: '🍜',
  },
  {
    id: 'm4',
    name: 'Soto Ayam Lamongan',
    category: 'Makanan Berat',
    price: 13000,
    stock: 12,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop&auto=format',
    description: 'Soto kuning gurih dengan suwiran ayam dan koya',
    emoji: '🍲',
  },
  {
    id: 'm5',
    name: 'Gado-Gado Jakarta',
    category: 'Makanan Berat',
    price: 12000,
    stock: 8,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop&auto=format',
    description: 'Sayuran rebus dengan bumbu kacang kental dan lontong',
    emoji: '🥗',
  },
  {
    id: 'm6',
    name: 'Nasi Uduk Komplit',
    category: 'Makanan Berat',
    price: 14000,
    stock: 10,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop&auto=format',
    description: 'Nasi uduk dengan ayam goreng, tempe, tahu, dan sambal',
    emoji: '🍱',
  },
  {
    id: 'm7',
    name: 'Es Teh Manis',
    category: 'Minuman',
    price: 5000,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop&auto=format',
    description: 'Teh manis segar dengan es batu',
    emoji: '🧋',
  },
  {
    id: 'm8',
    name: 'Jus Alpukat',
    category: 'Minuman',
    price: 12000,
    stock: 15,
    image: 'https://images.unsplash.com/photo-1638488388693-a81f4d03cf06?w=400&h=300&fit=crop&auto=format',
    description: 'Jus alpukat segar dengan susu kental manis',
    emoji: '🥤',
  },
  {
    id: 'm9',
    name: 'Es Jeruk Peras',
    category: 'Minuman',
    price: 8000,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop&auto=format',
    description: 'Jeruk lokal segar diperas langsung, manis segar',
    emoji: '🍊',
  },
  {
    id: 'm10',
    name: 'Indomie Goreng Spesial',
    category: 'Snack & Jajanan',
    price: 8000,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop&auto=format',
    description: 'Indomie goreng dengan telur, sosis, dan keju',
    emoji: '🍝',
  },
  {
    id: 'm11',
    name: 'Pisang Goreng Crispy',
    category: 'Snack & Jajanan',
    price: 7000,
    stock: 0,
    image: 'https://images.unsplash.com/photo-1598511756914-f77b6fd92e0f?w=400&h=300&fit=crop&auto=format',
    description: 'Pisang raja digoreng garing dengan taburan keju',
    emoji: '🍌',
  },
  {
    id: 'm12',
    name: 'Martabak Mini',
    category: 'Snack & Jajanan',
    price: 10000,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop&auto=format',
    description: 'Martabak telur mini dengan isian daging dan daun bawang',
    emoji: '🥚',
  },
];

export const demoUsers: User[] = [
  {
    id: 'u1',
    name: 'Rina Kartika',
    email: 'rina@student.ac.id',
    role: 'student',
    balance: 150000,
    nim: '2021050123',
  },
  {
    id: 'admin1',
    name: 'Pak Budi',
    email: 'admin@kantin.ac.id',
    role: 'admin',
    balance: 0,
  },
];

export const formatRupiah = (amount: number) =>
  new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(amount);
